name: Push
on:
  push:
    branches:
      - main

jobs:
  apply-changes:
    name: Apply changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - uses: pulumi/actions@v4
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.BJERKBOT_GITHUB_TOKEN }}
          PULUMI_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          command: up
          refresh: true
          stack-name: bjerk/prod
  
  todo-to-issue:
    name: Create issue from TODO comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Create issue from TODO comments 📝
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/)'
          label: needs-refinement
        env:
          GITHUB_TOKEN: ${{ secrets.BJERKIO_GITHUB_TOKEN }}
